# Generated by Django 3.2.20 on 2023-07-28 01:21

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0002_auto_20230711_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('time_submitted', models.DateTimeField()),
                ('approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='timeclock.employee')),
            ],
        ),
    ]
