# Generated by Django 3.2.20 on 2023-07-28 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0003_loa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loa',
            old_name='request',
            new_name='requestRange',
        ),
    ]
