# Generated by Django 3.2.20 on 2023-07-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0005_rename_requestrange_loa_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employed',
            field=models.BooleanField(default=True),
        ),
    ]
