# Generated by Django 3.2.20 on 2023-07-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0006_employee_employed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loa',
            name='request',
        ),
        migrations.RemoveField(
            model_name='loa',
            name='time_submitted',
        ),
        migrations.AddField(
            model_name='loa',
            name='date_submitted',
            field=models.DateField(default='2027-7-23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loa',
            name='requestEnd',
            field=models.DateField(default='2023-7-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loa',
            name='requestStart',
            field=models.DateField(default='2027-7-27'),
            preserve_default=False,
        ),
    ]
